export const PresaleContract = {
  abi: [
    {
      type: "constructor",
      inputs: [
        {
          name: "saleToken_",
          type: "address",
          internalType: "contract IERC20",
        },
        {
          name: "paymentToken_",
          type: "address",
          internalType: "address",
        },
        {
          name: "config",
          type: "tuple",
          internalType: "struct PresaleConfig",
          components: [
            { name: "startTime", type: "uint64", internalType: "uint64" },
            { name: "endTime", type: "uint64", internalType: "uint64" },
            { name: "rate", type: "uint256", internalType: "uint256" },
            { name: "softCap", type: "uint256", internalType: "uint256" },
            { name: "hardCap", type: "uint256", internalType: "uint256" },
            {
              name: "minContribution",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxContribution",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        { name: "owner_", type: "address", internalType: "address" },
        {
          name: "feeRecipient_",
          type: "address",
          internalType: "address",
        },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "FEE_BPS_DENOMINATOR",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "RATE_DIVISOR",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "addManyToWhitelist",
      inputs: [
        { name: "accounts", type: "address[]", internalType: "address[]" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "addToWhitelist",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "cancelPresale",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "claimEnabled",
      inputs: [],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "claimRefund",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "claimTokens",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "committedTokens",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "contribute",
      inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "contributions",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "depositSaleTokens",
      inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "endTime",
      inputs: [],
      outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "feeRecipient",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address payable" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "finalize",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "hardCap",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "isPaymentETH",
      inputs: [],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "maxContribution",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "minContribution",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "owner",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "paymentToken",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "proceedsClaimed",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "proceedsFeeBps",
      inputs: [],
      outputs: [{ name: "", type: "uint96", internalType: "uint96" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "proceedsFeesCollected",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "purchasedTokens",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "rate",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "refundsEnabled",
      inputs: [],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "removeFromWhitelist",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "renounceOwnership",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "saleToken",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "softCap",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "startTime",
      inputs: [],
      outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "tokenFeeBps",
      inputs: [],
      outputs: [{ name: "", type: "uint96", internalType: "uint96" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "tokenFeeCollected",
      inputs: [],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "tokenFeesCollected",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "tokensWithdrawn",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "totalRaised",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "totalTokensDeposited",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "transferOwnership",
      inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "updateConfig",
      inputs: [
        {
          name: "config",
          type: "tuple",
          internalType: "struct PresaleConfig",
          components: [
            { name: "startTime", type: "uint64", internalType: "uint64" },
            { name: "endTime", type: "uint64", internalType: "uint64" },
            { name: "rate", type: "uint256", internalType: "uint256" },
            { name: "softCap", type: "uint256", internalType: "uint256" },
            { name: "hardCap", type: "uint256", internalType: "uint256" },
            {
              name: "minContribution",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxContribution",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "updateFees",
      inputs: [
        {
          name: "newTokenFeeBps",
          type: "uint96",
          internalType: "uint96",
        },
        {
          name: "newProceedsFeeBps",
          type: "uint96",
          internalType: "uint96",
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "whitelist",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "withdrawProceeds",
      inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "withdrawUnusedTokens",
      inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "event",
      name: "ConfigUpdated",
      inputs: [
        {
          name: "config",
          type: "tuple",
          indexed: false,
          internalType: "struct PresaleConfig",
          components: [
            { name: "startTime", type: "uint64", internalType: "uint64" },
            { name: "endTime", type: "uint64", internalType: "uint64" },
            { name: "rate", type: "uint256", internalType: "uint256" },
            { name: "softCap", type: "uint256", internalType: "uint256" },
            { name: "hardCap", type: "uint256", internalType: "uint256" },
            {
              name: "minContribution",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxContribution",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ContributionReceived",
      inputs: [
        {
          name: "buyer",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "paymentAmount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "tokenAmount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "FeesUpdated",
      inputs: [
        {
          name: "tokenFeeBps",
          type: "uint96",
          indexed: false,
          internalType: "uint96",
        },
        {
          name: "proceedsFeeBps",
          type: "uint96",
          indexed: false,
          internalType: "uint96",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          name: "previousOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "newOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "PresaleFinalized",
      inputs: [
        {
          name: "successful",
          type: "bool",
          indexed: false,
          internalType: "bool",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ProceedsFeeCollected",
      inputs: [
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ProceedsWithdrawn",
      inputs: [
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "RefundClaimed",
      inputs: [
        {
          name: "buyer",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "TokenFeeCollected",
      inputs: [
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "TokensClaimed",
      inputs: [
        {
          name: "buyer",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "TokensDeposited",
      inputs: [
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "TokensWithdrawn",
      inputs: [
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "WhitelistUpdated",
      inputs: [
        {
          name: "account",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "allowed",
          type: "bool",
          indexed: false,
          internalType: "bool",
        },
      ],
      anonymous: false,
    },
    {
      type: "error",
      name: "AddressEmptyCode",
      inputs: [{ name: "target", type: "address", internalType: "address" }],
    },
    {
      type: "error",
      name: "AddressInsufficientBalance",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
    { type: "error", name: "AlreadyFinalized", inputs: [] },
    { type: "error", name: "ClaimNotEnabled", inputs: [] },
    { type: "error", name: "FailedInnerCall", inputs: [] },
    { type: "error", name: "HardCapReached", inputs: [] },
    { type: "error", name: "InvalidAmount", inputs: [] },
    { type: "error", name: "NotWhitelisted", inputs: [] },
    { type: "error", name: "NothingToClaim", inputs: [] },
    {
      type: "error",
      name: "OwnableInvalidOwner",
      inputs: [{ name: "owner", type: "address", internalType: "address" }],
    },
    {
      type: "error",
      name: "OwnableUnauthorizedAccount",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
    { type: "error", name: "RefundsNotEnabled", inputs: [] },
    {
      type: "error",
      name: "SafeERC20FailedOperation",
      inputs: [{ name: "token", type: "address", internalType: "address" }],
    },
    { type: "error", name: "SaleEnded", inputs: [] },
    { type: "error", name: "SaleNotActive", inputs: [] },
  ],
};

export const LaunchpadPresaleContract = PresaleContract;
